config/routes.rb
Rails.application.routes.draw do
  devise_for :users , path: '' , path_names: {sign_in: 'login',sign_out: 'logout',sign_up: 'register'}
  resources :portfolios
  
  get 'about' , to: 'pages#about'
  get 'contact',to:'pages#contact'
  get 'angular-items',to:'portfolios#angular'
  resources :blogs do 
    member do
      get:toggle_status
    end

  end



  root to: 'pages#home'





  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	extend FriendlyId

	enum status:{draft:0,published:1}
	  friendly_id :tittle, use: :slugged
	  validates_presence_of :tittle, :body
	
end

app/models/concerns/placeholder.rb
module Placeholder
	extend ActiveSupport::Concern
	def self.image_generator()
		"https://via.placeholder.com/300"
	end
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
	include Placeholder
	validates_presence_of :tittle,:body,:main_image,:thumb_image

	def self.angular
		where(subtittle:'Angular')
	end

	after_initialize :set_defaults

	def set_defaults
		self.main_image ||= Placeholder.image_generator
		
		self.thumb_image ||= Placeholder.image_generator
		
	end


end

app/models/skill.rb
class Skill < ApplicationRecord
	validates_presence_of :tittle,:percent_utilized

end

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of :tittle
	has_many : blogs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include DeviseWhitelists
	
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy toggle_status]

  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    

    redirect_to blogs_url


  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:tittle, :body)
    end
end

app/controllers/concerns/devise_whitelists.rb
module DeviseWhitelists
	extend ActiveSupport::Concern
	included do
		before_action :configure_permitted_parameters, if: :devise_controller?
	end
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up,keys: [:name])
		devise_parameter_sanitizer.permit(:account_update,keys: [:name])
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @blogs=Blog.all
    @skills=Skill.all
  end

  def about
  end

  def contact
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    before_action :set_portfolio, only: %i[ show edit update destroy ]

	def index
        @portfolios = Portfolio.all
    end
    #def angular
    #@angular_portfolio_items=Portfolio.angular 
    end

    def new
        @portfolios=Portfolio.new
    end

    def create
        @portfolios=Portfolio.new(params.require(:portfolio).permit(:tittle, :subtittle,:body))

        respond_to do |format|
            if @portfolios.save
            format.html { redirect_to (@portfolios), notice: "Portfolio was successfully created." }
            format.json { render :show, status: :created, location: @portfolios}
            end
        end
    end

    def show

    end

    def edit 

    end

    def update
    respond_to do |format|
      if @portfolio.update(params.require(:portfolio).permit(:tittle,:subtittle, :body))
        format.html { redirect_to portfolios_path, notice: "Portfolio was successfully updated." }
        format.json { render :show, status: :ok, location: @portfolio}
      
    end
end
end
def destroy
    @portfolio.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: "Portfolio was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  
    

    private

    def set_portfolio
        @portfolio = Portfolio.find_by_id(params[:id])
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tittle %>
    <%= form.text_field :tittle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Tittle</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.tittle %></td>
        <td><%= blog.body %></td>
         <td><%=link_to blog.status, toggle_status_blog_path(blog) %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tittle:</strong>
  <%= @blog.tittle %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeccampPortfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>


       <% if current_user %>
       <%= link_to "Logout" ,destroy_user_session_path , method: :delete %>
       <%else%>
       <%= link_to "Login" ,new_user_session_path %>
       <%= link_to "Register" ,new_user_registration_path %>
       <%end%>



    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>HomePage</h1>

<p>Find me in app/views/pages/home.html.erb</p>
<h1>Blogs</h1>
<%=@blogs.inspect%>
<h1>Skills</h1>
<%=@skills.inspect%>

app/views/portfolios/angular.html.erb
<%= link_to"Angular items" ,new_portfolio_url %>


<h1>Portfolios</h1>
<% @angular_portfolio_items.each do |portfolio_item|%>
<p> <%= link_to portfolio_item.tittle ,portfolio_path(portfolio_item) %>   </p>
<p> <%=portfolio_item.subtittle %>   </p>
<p> <%=portfolio_item.body %>   </p>
 <%=image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>   
 <%= link_to"Edit" ,edit_portfolio_url(portfolio_item.id) %>
 <%= link_to 'Destroy', portfolio_path(portfolio_item.id), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>	

app/views/portfolios/edit.html.erb
<%= form_for(@portfolio) do |form| %>


  <div class="field">
    <%= form.label :tittle %>
    <%= form.text_field :tittle %>
  </div>
  <div class="field">
    <%= form.label :subtittle %>
    <%= form.text_field :subtittle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

 <% end %>

app/views/portfolios/index.html.erb
<%= link_to"Add new portfolio" ,new_portfolio_url %>


<h1>Portfolios</h1>
<% @portfolios.each do |portfolio_item|%>
<p> <%= link_to portfolio_item.tittle ,portfolio_path(portfolio_item) %>   </p>
<p> <%=portfolio_item.subtittle %>   </p>
<p> <%=portfolio_item.body %>   </p>
 <%=image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>   
 <%= link_to"Edit" ,edit_portfolio_url(portfolio_item.id) %>
 <%= link_to 'Destroy', portfolio_path(portfolio_item.id), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>	

app/views/portfolios/new.html.erb
<%= form_for(@portfolios) do |form| %>
  <div class="field">
    <%= form.label :tittle %>
    <%= form.text_field :tittle %>
  </div>
  <div class="field">
    <%= form.label :subtittle %>
    <%= form.text_field :tittle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

 <% end %>

app/views/portfolios/show.html.erb
<P id="notice"><%= notice %></p>
  <%= image_tag @portfolio.main_image%>
<p>
  <h1>tittle:</h1>
  <%= @portfolio.tittle %>
</p>
<p>
  <em>subTittle:</em>
  <%= @portfolio.subtittle %>
</p>

<p>
  <p>Body:</p>
  <%= @portfolio.body %>
</p>